gecoscc/__init__.py
gecoscc/models.py

This patch must fix issue #16 (Error accessing global Settings)

Fix unicode string problem (Issue #16)

---

config-templates/development.ini
gecoscc/__init__.py
gecoscc/permissions.py
gecoscc/templates/base_navbar.jinja2
gecoscc/templates/server/connections.jinja2
gecoscc/templates/server/log.jinja2
gecoscc/templates/server/status.jinja2
gecoscc/utils.py
gecoscc/views/portal.py
gecoscc/views/server.py

Please take into consideration this patch for Issue #12 and send me any comments about it.
Thanks

Path for Issue #12

---

gecoscc/tasks.py
gecoscc/tests.py

Disassociate from groups

---

gecoscc/api/__init__.py
gecoscc/tests.py

1 - Fix #27 
2 - Improve tests

Visibility nodes

---

gecoscc/tasks.py
gecoscc/tests.py

Test and code improvements

---

config-templates/development.ini
gecoscc/views/server.py

Please consider this patch to fix hardcoded "http".
Basically I moved the URL patters to "gecoscc.ini" file.
Best regards

Issue #22 - Log & status rest api (fix hardcoded "http")

---

gecoscc/utils.py

Now can add software profile policy to workstation

---

config-templates/development.ini
gecoscc/utils.py

Added temporary solution to the concurrency problem

---

gecoscc/commands/import_policies.py
gecoscc/models.py
gecoscc/static/js/libs/jsonform-b3-1.0.0.js
gecoscc/templates/base_tree.jinja2
gecoscc/templates/settings.jinja2
gecoscc/views/settings.py

Reverts gecos-team/gecoscc-ui#49 
Pull Request will go to development branch

Revert "New settings added. Mimetype collection for form autocomplete"

---

gecoscc/templates/bb-printer.html

changed the fields order to show important information in the top of the template.

changed printers template in order to be more intuitive

---

gecoscc/models.py

Changed policy name to Kerberos-AD

changed negotiate to kerberos-ad

---

gecoscc/api/chef_status.py
gecoscc/tasks.py
gecoscc/utils.py

When registering a new user in the control center, to detect the computers in which he is already a user and to update the list

Update the list of computers on which a new user is registered in GCC.

---

gecoscc/api/__init__.py
gecoscc/api/chef_status.py
gecoscc/api/nodes.py
gecoscc/commands/update_ip_address.py
gecoscc/commands/update_ip_addresses.py
gecoscc/static/css/scp-gecos.css
gecoscc/static/js/app.js
gecoscc/static/js/tree-views.js
gecoscc/static/js/tree.js
gecoscc/templates/base_tree.jinja2

With these changes the tree search functionality now searches by node name, by username of the user that has used a computer, and by computer IP address.

Added tree search functionality

---

gecoscc/api/jobs_statistics.py
gecoscc/api/my_jobs_statistics.py
gecoscc/commands/update_jobs_to_macrojobs.py
gecoscc/static/css/fuelux.css
gecoscc/static/css/scp-gecos.css
gecoscc/static/js/app.js
gecoscc/static/js/jobs.js
gecoscc/static/js/tree-views-renderer.js
gecoscc/templates/base_tree.jinja2
gecoscc/templates/bb-jobs-summary.html
gecoscc/templates/bb-jobs.html

* Change the minimized view of the tasks list by a tasks summary. With this change the nodes tree has more vertical space.
* When a node of the tree has a large name the name is truncated. The user can see the complete name as a tooltip when the mouse is over the node.
* Added a handler to change nodes tree horizontal size. Just click in the handler and move the mouse right or left to change the nodes tree horizontal size.
* Changed vertical separator line widh. The vertial separator line (line that appears when you open an organizational line of the tree) is now bigger.

Tree improvements

---

gecoscc/static/js/tree-views.js
gecoscc/templates/base_tree.jinja2

Launch search on dropdown hide event

Launch search on dropdown hide event

---

gecoscc/static/css/scp-gecos.css
gecoscc/static/js/ou.js
gecoscc/static/js/tree-views-renderer.js
gecoscc/static/js/tree-views.js
gecoscc/static/js/tree.js
gecoscc/templates/bb-tree-search.html

With this change the filtering of the tree nodes is made by Javascript without searching in the database. So, it isn't a search filter any more, it's just a visibility filter.

More dynamic filter.

---

gecoscc/api/__init__.py
gecoscc/tasks.py
gecoscc/utils.py

Bugfix: 
gecoscc/api/__init__.py
Missing "action" parameter. 
object_action method in tasks.py not receives this param

New merge algorithm

---

gecoscc/static/css/scp-gecos.css
gecoscc/static/js/computer.js

* Set blue color for null and boolean values.
* Add comma after values where appropriate.

Format fix

---

gecoscc/commands/check_local_groups_policy.py
gecoscc/tasks.py
gecoscc/utils.py

- New command for migrating to new policy schema (check_local_groups_policy).
- New method trace_inheritance for saving inheritance of every node.

Local groups policy merge

---

gecoscc/static/js/user.js

Bugfix "uncaught exception: Container collections require a search_filter attribute" when user node is clicked on the tree.

Bugfix search filter user

---

gecoscc/commands/migrate_to_chef12.py

Unneeded workaround, just updating CHEF to 12.16.9,

Revert "Fix ACL problems when there is an actor that could be a user or a client"

---

gecoscc/rules.py
gecoscc/tasks.py
gecoscc/utils.py

With these patches we avoid unnecessary jobs creation.

Fix jobs creation

---

gecoscc/static/js/app-utils.js
gecoscc/static/js/group-form-views.js
gecoscc/static/js/inheritance.js

'items undefined' javascript error when we create new object in Gecos GUI.

Bugfix items undefined

---

gecoscc/api/__init__.py
gecoscc/api/computers.py
gecoscc/commands/check_node_policies.py
gecoscc/models.py
gecoscc/permissions.py
gecoscc/static/css/scp-gecos.css
gecoscc/static/js/inheritance.js
gecoscc/tasks.py
gecoscc/templates/bb-computer.html
gecoscc/templates/bb-groups-form.html
gecoscc/templates/bb-inheritance.html
gecoscc/templates/bb-ou.html
gecoscc/templates/bb-user.html
gecoscc/utils.py

Modifies the "inheritance" field to store a tree with the policies inheritance information.
Also shows the inheritance tree in the frontend.

Policies inheritance tree

---

gecoscc/locale/es/LC_MESSAGES/gecoscc.po

Changed wrong translations of 2 page headers

---

gecoscc/api/jobs.py

Propagating filter by workstation on microjobs.

Logbook: filtering by workstation on microjobs

---

gecoscc/__init__.py
gecoscc/templates/base.jinja2
gecoscc/templates/server/status.jinja2
gecoscc/views/server.py

Display cookbooks info in the status page and server address in the right area of the footer.

More status info

---

gecoscc/static/js/libs/jsonform-b3-1.0.0.js
gecoscc/static/js/policies-form-generator.js

- Implements schema dependencies
https://github.com/json-schema/json-schema/wiki/Dependencies#schema-dependencies

JSONForm: dependencies and customForItems added

---

gecoscc/db.py
gecoscc/scripts/chef_backup.sh
gecoscc/scripts/chef_restore.sh
gecoscc/utils.py

- This plugin currently supports Enterprise Chef 11 and Chef Server 12 https://github.com/chef/knife-ec-backup
- Control errors added for updates functions.

knife-ec-backup plugin

---

gecoscc/utils.py

mongo cursor is timing out on the server (after 10 minutes of inactivity).

Bugfix pymongo error cursor id not valid

---

gecoscc/commands/check_local_admin_policy.py
gecoscc/commands/check_node_policies.py
gecoscc/utils.py

- Suppress warning messages (Unverified HTTPS request).
- FIXED string added to check_node_policies command.
- Changes error message by warning message in check_local_admin_policy command.

check commands logging

---

gecoscc/rules.py

- Users policy:
A user without a password generates KeyError exception

Bugfix: Keyerror password exception

---

gecoscc/api/serviceproviders.py
gecoscc/commands/import_policies.py
gecoscc/commands/mobile_broadband_providers.py
gecoscc/models.py
gecoscc/static/js/jsonform-utils.js
gecoscc/static/js/libs/jsonform-b3-1.0.0.js

- New serviceproviders collection added.
- Autocomplete_url for countries and providers fields in mobile broadband policy.

Mobile broadband optimized

---

gecoscc/commands/check_packages_policy.py

Decreases execution time avoiding no-needed recursivity

check_packages_policy migration script optimized.

---

config-templates/development.ini
gecoscc/commands/check_local_admin_policy.py
gecoscc/commands/check_local_file_policy.py
gecoscc/commands/check_local_groups_policy.py
gecoscc/commands/check_local_users_policy.py
gecoscc/commands/check_node_policies.py
gecoscc/commands/check_packages_policy.py
gecoscc/commands/check_user_apps_autostart_policy.py
gecoscc/commands/check_user_launchers_policy.py
gecoscc/management.py

- Uses logger configuration from gecoscc.ini file

Root logger for migration scripts

---

gecoscc/static/js/libs/jsonform-b3-1.0.0.js

Fixed: "country" field dissapeared.

Fix mobile broadcand editform

---

gecoscc/api/admin_users.py
gecoscc/api/gca_ous.py
gecoscc/models.py
gecoscc/utils.py
gecoscc/views/admins.py

Administrators can manage several OUs. Now, the variable configuration form allows admin to add gem sources for each OU managed by him.

Setting up multitenant gem sources by admin

---

gecoscc/api/computers.py
gecoscc/api/help_channel_client.py
gecoscc/static/js/computer.js
gecoscc/templates/bb-computer.html
requirements.txt

Changes to integrate Help Channel with GECOS Control Center.

Help channel integration

---

gecoscc/__init__.py
gecoscc/static/css/scp-gecos.css
gecoscc/static/js/computer.js
gecoscc/templates/base_navbar.jinja2
gecoscc/templates/report.jinja2
gecoscc/templates/reports.jinja2
gecoscc/views/report_computer.py
gecoscc/views/report_printers.py
gecoscc/views/report_user.py
gecoscc/views/reports.py
requirements.txt

First version of printers report

Printers report

---

gecoscc/templates/report.jinja2
gecoscc/templates/reports.jinja2
gecoscc/views/report_computer.py
gecoscc/views/report_printers.py
gecoscc/views/report_user.py
gecoscc/views/reports.py

- New values for columns width
- Links for html view
- Parent window navigation from report view

Reports optimized

---

gecoscc/static/js/libs/jsonform-b3-1.0.0.js

There was an English translation issue in remote control policy.

Fix English language translation issue

---

gecoscc/views/reports.py

The OUs will be alphabetically  sorted (ignoring case).

Fix OUs sorting in report page.

---

gecoscc/__init__.py
gecoscc/api/__init__.py
gecoscc/commands/check_node_policies.py
gecoscc/utils.py
requirements.txt

Use case insensitive search to forbid the creation of two OUs with the same name.

Fix53834 v2

---

gecoscc/utils.py
gecoscc/views/reports.py

Bugfix: when the user clicked in the log out button after the session expired a record was recorded in the audit log with an empty username.

Fix audit log

---

gecoscc/api/ad_import.py
gecoscc/api/chef_client_run.py
gecoscc/tasks.py
gecoscc/tests.py
gecoscc/utils.py

Reverts gecos-team/gecoscc-ui#223

Revert "Mutex with MongoDB findAndModify action"

---

gecoscc/api/computers.py
gecoscc/commands/recalc_nodes_policies.py
gecoscc/tasks.py
gecoscc/utils.py

Improve "recalc_node_policies" script performance.

"recalc_node_policies" script optimization

---

config-templates/development.ini
gecoscc/__init__.py
gecoscc/socks.py
gecoscc/tasks.py
gecoscc/templates/reports.jinja2
gecoscc/views/report_no_computer_users.py
gecoscc/views/report_no_user_computers.py
requirements.txt

Some libraries update as a first step to a future migration to Python 3

Libraries update
