gecoscc/tasks.py

When we deleted objects with related policies within the same node, and those policies were related with policy emitter objects (printers, repositories, software profile and shared folders), an error was produced.

Fixed little error when deleting policies with policy emitter objects

---

gecoscc/tasks.py

As a result of deleting a previous block of code that is left over, the conditional structure has been corrected

Bugfix: Syntax error elif 511 line

---

config-templates/development.ini
gecoscc/commands/create_chef_administrator.py
gecoscc/commands/import_chef_nodes.py
gecoscc/commands/import_policies.py
gecoscc/commands/migrate_to_chef12.py
gecoscc/forms.py
gecoscc/templates/admins/edit.jinja2
gecoscc/tests.py
gecoscc/utils.py
gecoscc/views/admins.py

Because Chef 12 has multitenancy based on organizations, to use Chef 12, the GECOS structure is stored in the "default" organization.
Also, the clients with "admin" permissions dissapear, and the users can't create nor delete other users if such permissions aren't granted by using the "chef-server-ctl grant-server-admin-permissions" command.
This pull request contains the minimum changes to use GECOS CC with Chef 12 server.
Also, a "migrate_to_chef12" command is added. This command checks the user permissions and the computer ACLs and fix them is necessary. This script may be launched after migrating from Chef 11 to Chef 12.

Changes to use Chef 12 server instead of Chef 11

---

config-templates/development.ini

Added configuration for the 'pyramid_beaker' module to set a session timeout of 20 minutes and to destroy the session when the user closes the browser.
More info about Beaker configuration in:
http://beaker.readthedocs.io/en/latest/configuration.html#session-options

Added default session timeout setting it to 20 minutes.

---

gecoscc/commands/check_node_policies.py
gecoscc/commands/migrate_to_chef12.py

* migrate_to_chef12: Some bugfixes.
* check_node_policies: Script that checks the MongoDB database for problems. Reports all the errors found and fixes relationship problems by deleting the relationship. For example, if a user is supposed to be related with a computer that doesn't exists in the database, that relationship is deleted.
These scripts are used after a migration from Chef 11 to Chef 12 to ensure that the system will work properly.

Scripts to upgrade to Chef 12

---

gecoscc/utils.py

Import DELETED_POLICY_ACTION constant from gecoscc.tasks

Bugfix global name 'DELETED_POLICY_ACTION' is not defined

---

gecoscc/tasks.py

When field_ui is callable, then obj_ui has already been applied to the particular function. It is not necessary to reapply it or in this case the comparison with objold_ui will always be different,  generating a task of more

Bugfix get_merge_policies: field_ui callable not generate jobs well.

---

gecoscc/forms.py

This code line produces an error: Invalid cross-device link.
os.rename(tmpdir, cookbook_path)
From python documentation (https://docs.python.org/2/library/os.html)
"Rename the file or directory src to dst. If dst is a directory, OSError will be raised. On Unix, if dst exists and is a file, it will be replaced silently if the user has permission. **The operation may fail on some Unix flavors if src and dst are on different filesystems**. If successful, the renaming will be an atomic operation (this is a POSIX requirement). On Windows, if dst already exists, OSError will be raised even if it is a file; there may be no way to implement an atomic rename when dst names an existing file"
Replace the line of code with this one:
shutil.move(tmpdir, cookbook_path)

Bugfix Cookbook Upload: Invalid cross-device link

---

gecoscc/socks.py

Gevent doesn't change from `http` to `https` protocol and, in case you configure NGINX to use only secure server, you'll get frontpage without styles sheets.
This PR makes `gevent` to use the enviroment variables to know if the protocol is `http` or `https`.

Fix bad https redirections in Nginx

---

gecoscc/commands/create_chef_administrator.py

The if statement returns True or False and the code was looking for None. It is solved now and GECOSCC administrator users may be created.

fixed an issue creating GECOSCC administrator users

---

gecoscc/rules.py
gecoscc/tasks.py

- Detecting changes in policy by comparison between obj and objold.
- Logging errors (traceback).
- Conversion of the username format from mongo to Chef in has_changed_* methods.
- Defaults for empty fields in objects.

"No save in chef server. 'NoneType' object has no attribute 'get'"

---

gecoscc/tasks.py

- When an item of a policy is deleted, its value in Chef wasn't updated.
- Chef doesn't accept dots in usernames, so methods `has_changed` cannot find this malformed usernames to update its policy values.

Bugfix has_changed methods

---

gecoscc/tasks.py
gecoscc/utils.py

- "has_changed_user_policy" method raises "Keyerror" exception when objold_ui is an empty object ({}).
- "validate_data" method raises "initial_value referenced before assignment" exception when attribute type is a boolean.
-  Ignore a non user policy in a computer calculated by "get_computer_of_user" method

Hotfix: 'Keyerror' and 'initial_value referenced before assignment' exceptions

---

gecoscc/api/register_computer.py
gecoscc/tasks.py

Fix a bug that happened when "object_detached" tried to remove a Chef node that was already deleted by /register/node

Bugfix: doble deletion of node

---

gecoscc/scripts/chef_backup.sh
gecoscc/scripts/chef_restore.sh
gecoscc/utils.py

Overrides default behaviour of plugin with webui-key option. 
Useful in case of chef server is in a different machine of Gecos Control Center

Knife EC plugin with webui-key option

---

gecoscc/db.py

DEFAULT_EXCLUDE_COLLECTIONS option added.  'updates' and 'backer_cache' collections must be ignored in mongo backup by default because if they would be restored, updates system not working properly.

Exclude collections

---

gecoscc/api/register_chef_node.py

TypeError: unbound method rekey() must be called with Client instance as first argument (got ChefAPI instance instead)
Error: invoking class method instead instance method.

Bugfix: unbound method rekey()

---

gecoscc/filters.py
gecoscc/templates/base_navbar.jinja2

If you stop using the GECOS CC for a long time and your session expires, when you use any functionality that uses AJAX there is an error in the server due to the non existence of the user session data.
This can be tested with CURL:
` curl -X GET -H "Content-type: application/json" -H "Accept: application/json"  "http://<SERVER>/api/nodes/?iname=depar&search_by=nodename&type=&page=1&pagesize=10&_=1572002868893"`
This patch checks that user is not None in the JINJA template and checks that the user can be JSON serialized.

Fix forbidden page visualization.

---

gecoscc/static/js/app.js

This bug appeared when you search for something, for example "ESPA", and that search returns two many nodes in the tree. So you search again for example "informacionESPA", and when you select that node you can see that in the nodes tree instead of loading the "informacionESPA" node location is loaded the previous search results.
This patch fixes that bug.

Fix a bug in the nodes tree that appeared after searching twice.

---

gecoscc/commands/check_node_policies.py
gecoscc/tasks.py
gecoscc/utils.py

Changes to check "gecos_path_ids" and "gecos_path_names" fields in "check_node_policies" script, lock the Chef nodes before adding/modifying "gecos_path_ids" and "gecos_path_names" fields, and fix  "gecos_path_names" field calculation.

Fix "gecos_path_names" and "gecos_path_ids" information in Chef Node.
